# Generated by Django 4.2.7 on 2025-11-28 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettype",
            name="event",
        ),
        migrations.RemoveField(
            model_name="event",
            name="allow_tickets",
        ),
        migrations.DeleteModel(
            name="TicketPurchase",
        ),
        migrations.DeleteModel(
            name="TicketType",
        ),
    ]
