# Generated by Django 5.2.4 on 2025-08-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestion',
            name='download_count',
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='file',
            field=models.URLField(),
        ),
    ]
