# Generated by Django 5.2.4 on 2025-08-29 14:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_pastquestion_download_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='news/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='schools/'),
        ),
    ]
