# Generated by Django 5.2.4 on 2025-09-06 07:29

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_featured_image_alter_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastquestion',
            options={'ordering': ['-start_year', '-end_year', 'subject']},
        ),
        migrations.RenameField(
            model_name='pastquestion',
            old_name='year',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='pastquestion',
            old_name='file',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='published_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_image/'),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='start_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
