# Generated by Django 4.2.7 on 2025-12-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_pastquestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="featured_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
