# Generated by Django 5.0 on 2026-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_news_featured_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
