# Generated by Django 4.2.7 on 2026-02-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_category_slug_alter_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
