# Generated by Django 4.2.28 on 2026-05-03 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header", "Header Banner"),
                            ("body", "Body Banner"),
                            ("footer", "Footer Banner"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("max_advertisers", models.IntegerField(default=5)),
                (
                    "duration_days",
                    models.IntegerField(
                        default=30, help_text="How long one ad booking lasts (days)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "advertiser_name",
                    models.CharField(
                        help_text="Business / brand name shown on the ad",
                        max_length=200,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ad headline (max 100 chars)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description (max 300 chars)",
                        max_length=300,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload your banner image (JPG/PNG, max 2MB)",
                        null=True,
                        upload_to="ads/banners/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Auto-filled from uploaded image",
                        null=True,
                    ),
                ),
                (
                    "cloudinary_public_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Learn More",
                        help_text="Call-to-action button text",
                        max_length=50,
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(
                        help_text="Where to send visitors when they click the ad"
                    ),
                ),
                (
                    "ad_format",
                    models.CharField(
                        choices=[
                            ("image", "Image Banner"),
                            ("text", "Text Ad"),
                            ("image_text", "Image + Text"),
                        ],
                        default="image_text",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved — Live"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not shown publicly)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisements",
                        to="ads.adslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impression_logs",
                        to="ads.advertisement",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_logs",
                        to="ads.advertisement",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
