# Generated by Django 4.2.28 on 2026-05-03 21:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="ads/banners/"
            ),
        ),
    ]
