# Generated by Django 5.0 on 2025-12-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video URL for tutorial",
                max_length=500,
                null=True,
            ),
        ),
    ]
