# Generated by Django 5.0 on 2026-01-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0003_material_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pdf", "PDF Document"),
                    ("text", "Text Content"),
                    ("image", "Image"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
