# Generated by Django 4.2.28 on 2026-02-23 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0004_alter_material_material_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (100, "100 Level"),
                            (200, "200 Level"),
                            (300, "300 Level"),
                            (400, "400 Level"),
                            (500, "500 Level"),
                            (600, "600 Level"),
                            (700, "700 Level"),
                        ]
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("first", "First Semester"),
                            ("second", "Second Semester"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True, help_text="e.g. 2023/2024", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level", "semester"],
                "unique_together": {("student", "level", "semester")},
            },
        ),
        migrations.CreateModel(
            name="CourseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=20)),
                ("course_title", models.CharField(max_length=200)),
                ("credit_units", models.PositiveSmallIntegerField(default=2)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A  (70 – 100)"),
                            ("B", "B  (60 – 69)"),
                            ("C", "C  (50 – 59)"),
                            ("D", "D  (45 – 49)"),
                            ("E", "E  (40 – 44)"),
                            ("F", "F  (0  – 39)"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Raw score out of 100 (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="learning.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["course_code"],
            },
        ),
    ]
