# Generated by Django 4.2.7 on 2026-02-13 04:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tickets.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("party", "Party"),
                            ("concert", "Concert"),
                            ("festival", "Festival"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("sports", "Sports"),
                            ("other", "Other"),
                        ],
                        default="party",
                        max_length=20,
                    ),
                ),
                ("venue", models.CharField(max_length=300)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(default="Rivers State", max_length=100)),
                ("event_date", models.DateTimeField()),
                ("doors_open", models.TimeField(help_text="What time do doors open?")),
                (
                    "event_start",
                    models.TimeField(help_text="What time does the event start?"),
                ),
                ("event_end", models.TimeField(blank=True, null=True)),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "early_bird_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional early bird discount price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "early_bird_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="When does early bird pricing end?",
                        null=True,
                    ),
                ),
                (
                    "total_tickets",
                    models.PositiveIntegerField(
                        help_text="Total number of tickets available"
                    ),
                ),
                ("tickets_sold", models.PositiveIntegerField(default=0)),
                (
                    "banner_image",
                    models.ImageField(
                        help_text="Main event banner (recommended: 1200x600px)",
                        upload_to="events/banners/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image (recommended: 400x400px)",
                        null=True,
                        upload_to="events/thumbnails/",
                    ),
                ),
                ("organizer_name", models.CharField(max_length=200)),
                ("organizer_phone", models.CharField(max_length=20)),
                ("organizer_email", models.EmailField(max_length=254)),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="Event features, one per line (e.g., 'Live DJ', 'Free drinks', 'VIP lounge')",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="TicketPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price_per_ticket",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(max_length=200, unique=True)),
                (
                    "paystack_reference",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="tickets.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_code",
                    models.CharField(
                        default=tickets.models.generate_ticket_code,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("scanned_by", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tickets.event",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tickets.ticketpurchase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_date"], name="tickets_eve_event_d_0dbc20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="tickets_eve_status_3576f7_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_active"], name="tickets_eve_is_acti_85c95c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketpurchase",
            index=models.Index(
                fields=["payment_reference"], name="tickets_tic_payment_8c18a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketpurchase",
            index=models.Index(fields=["email"], name="tickets_tic_email_b77f37_idx"),
        ),
        migrations.AddIndex(
            model_name="ticketpurchase",
            index=models.Index(
                fields=["payment_status"], name="tickets_tic_payment_92ca20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_code"], name="tickets_tic_ticket__b86ea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="tickets_tic_status_0e5646_idx"),
        ),
    ]
