# Generated by Django 4.2.7 on 2026-02-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_phone",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="state",
            field=models.CharField(default="Rivers State", max_length=200),
        ),
    ]
