# Generated by Django 4.2.7 on 2026-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_event_city_alter_event_organizer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_email",
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_phone",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="event",
            name="state",
            field=models.CharField(default="Rivers State", max_length=250),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="scanned_by",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("used", "Used"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="ticketpurchase",
            name="first_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="ticketpurchase",
            name="last_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="ticketpurchase",
            name="payment_reference",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="ticketpurchase",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="ticketpurchase",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="ticketpurchase",
            name="verified_by",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
