# Generated by Django 4.2.7 on 2026-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_alter_event_city_alter_event_organizer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
