# Generated by Django 4.2.7 on 2026-02-13 04:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_alter_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="banner_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Main event banner (recommended: 1200x600px)",
                max_length=255,
                null=True,
                verbose_name="event/banner",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Thumbnail image (recommended: 400x400px)",
                max_length=255,
                null=True,
                verbose_name="events/thumbnails/",
            ),
        ),
    ]
